### ISSUE TITLE
BNZ fails to authenticate due to server error

### ISSUE THREAD

**Issue by servilla** [PASTAplus/auth#6]
BNZ fails to authenticate due to server error:

> 2020-10-02 12:19:15,455 [1545] ERROR    webapp.routes: Exception on /auth/login/pasta [GET]
> Traceback (most recent call last):
>   File "/home/pasta/anaconda3/envs/auth/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/pasta/anaconda3/envs/auth/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/pasta/anaconda3/envs/auth/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/pasta/anaconda3/envs/auth/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
>     raise value
>   File "/home/pasta/anaconda3/envs/auth/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/pasta/anaconda3/envs/auth/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "./webapp/routes.py", line 83, in login
>     credentials = base64.b64decode(authorization.strip('Basic ')).\
>   File "/home/pasta/anaconda3/envs/auth/lib/python3.7/base64.py", line 87, in b64decode
>     return binascii.a2b_base64(s)
> binascii.Error: Incorrect padding

**Comment by servilla** [comment]
Bit by the ridiculously named Python "strip" function:
`credentials = base64.b64decode(authorization.strip('Basic ')).decode('utf-8')`

Replaced with
`credentials = base64.b64decode(authorization[6:]).decode('utf-8')`

The purpose of this code is to remove the "Basic " substring from the HTTP Authorization header so that it may be correctly Base64 decoded:
"Basic dWlkPUJOWixvPUVESSxkYz1lZGl..."
