### ISSUE TITLE
name value returns None from GitHub OAuth response

### ISSUE THREAD

**Issue by servilla** [PASTAplus/auth#7]
User Stephani Schupbach reported an internal server error response when attempting to login into ezEML using his GitHub acccount.

> On Fri, Oct 30, 2020 at 1:05 PM Schupbach, Stephani A <Stephani_Schupbach@contractor.nps.gov> wrote:
> I watched the EZEml video a few weeks ago and would like to try the tool. When I tried to login with my GitHub account, I received this error. Is the server really down or is it possible my DOI firewall is blocking my login?

**Comment by servilla** [comment]
Investigation showed that the GitHub OAuth response json, although containing a "name" field, the "name" field was set to the `None` object. This resulted in a downstream parsing error:

```
Traceback (most recent call last):
  File "/home/pasta/anaconda3/envs/auth/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pasta/anaconda3/envs/auth/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pasta/anaconda3/envs/auth/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pasta/anaconda3/envs/auth/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pasta/anaconda3/envs/auth/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pasta/anaconda3/envs/auth/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./webapp/routes.py", line 179, in github_callback
    redirect_url = make_target_url(target, auth_token, cname)
  File "./webapp/routes.py", line 327, in make_target_url
    _cname = urllib.parse.quote(cname)
  File "/home/pasta/anaconda3/envs/auth/lib/python3.7/urllib/parse.py", line 834, in quote
    return quote_from_bytes(string, safe)
  File "/home/pasta/anaconda3/envs/auth/lib/python3.7/urllib/parse.py", line 859, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes
```
The routes.py code that handles the GitHub response should test for `None` in both the `name` and `login` fields of the json response: if both are `None`, the `cname` attribute should be set to a default string (e.g., `unknown user`).
